### ISSUE TITLE
NameError: name 'modTupByIndex' is not defined

### ISSUE THREAD

**Issue by tampix** [jonnyrobbie/mal-gantt#1]
Hello,

I have trouble trying your tool on my end.
Don't know if it's a problem of configuration on my end or not, but i have this error : 
```
Traceback (most recent call last):               
  File "./mal_gantt.py", line 235, in <module>   
    chart.draw()                                 
  File "./mal_gantt.py", line 214, in draw       
    self.chart.drawGrid(majColor=args.majcolour, minColor=args.mincolour, textColor=args.lgridcolour)                                                                                               
  File "./mal_gantt.py", line 78, in drawGrid    
    modTupByIndex(self.currentTuple, 2, 1)       
NameError: name 'modTupByIndex' is not defined
```

```
> uname -a; python --version
Linux arch 4.11.9-1-ARCH #1 SMP PREEMPT Wed Jul 5 18:23:08 CEST 2017 x86_64 GNU/Linux
Python 3.6.2
```

Params used : 
```
./mal_gantt.py --open animelist_1515433548_-_5084583.xml --fontfile /usr/share/fonts/TTF/DejaVuSansMono.ttf
```
(so pretty standard font)

I can attach my export too if it's necessary.

**Comment by tampix** [comment]
Saw your commit, tried with it and it works.
I let you decide if the issue is closed or not :)

**Comment by jonnyrobbie** [comment]
Yeah, there was one line I forgot. Can you pull and try it now? If it doesn't work, I may need to have a look at your export.

**Comment by jonnyrobbie** [comment]
By the way, just out of curiosity, can you share the result? I'd be really curious how it works for others. :)

**Comment by tampix** [comment]
Ah sorry my bad, seems like i didn't check the image properly beforehand ...
Something seems a little bit fishy there : 
https://imgur.com/a/hocD8
https://pastebin.com/FjBbDhLm

**Comment by tampix** [comment]
Ok i checked ... for some reason the start date in my list is always 0000-00-00 ... guess i'll try to fix my list then (but i think this is a desperate case for me then x) )

[edit]
(As for the reason, well i almost never follow the only working flow, that is : https://myanimelist.net/forum/?topicid=1634296)
